export const PERMISSIONS = [
  "VISITANTES_CADASTRAR",
  "VISITANTES_LISTAR",
  "VISITANTES_EDITAR",
  "VISITANTES_EXCLUIR",
  "VISITANTES_EXPORTAR",
  "CULTO_INFANTIL_SELECIONAR",
  "MENSAGENS_GERENCIAR",
  "MENSAGENS_ENVIAR",
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];

export const Permission: Record<PermissionKey, PermissionKey> = {
  VISITANTES_CADASTRAR: "VISITANTES_CADASTRAR",
  VISITANTES_LISTAR: "VISITANTES_LISTAR",
  VISITANTES_EDITAR: "VISITANTES_EDITAR",
  VISITANTES_EXCLUIR: "VISITANTES_EXCLUIR",
  VISITANTES_EXPORTAR: "VISITANTES_EXPORTAR",
  CULTO_INFANTIL_SELECIONAR: "CULTO_INFANTIL_SELECIONAR",
  MENSAGENS_GERENCIAR: "MENSAGENS_GERENCIAR",
  MENSAGENS_ENVIAR: "MENSAGENS_ENVIAR",
};

export const PERMISSIONS_BY_MODULE = {
  Visitantes: [
    Permission.VISITANTES_CADASTRAR,
    Permission.VISITANTES_LISTAR,
    Permission.VISITANTES_EDITAR,
    Permission.VISITANTES_EXCLUIR,
    Permission.VISITANTES_EXPORTAR,
  ],
  "Culto Infantil": [Permission.CULTO_INFANTIL_SELECIONAR],
  Mensagens: [Permission.MENSAGENS_GERENCIAR, Permission.MENSAGENS_ENVIAR],
} as const;
